// <auto-generated />
using KursPortal.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KursPortal.Migrations
{
    [DbContext(typeof(KursPortalDBContext))]
    [Migration("20261008073421_KursPortalMigration")]
    partial class KursPortalMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KursPortal.Models.Kurs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnzahlTeilnehmer")
                        .HasColumnType("int");

                    b.Property<int>("DauerInTagen")
                        .HasColumnType("int");

                    b.Property<string>("Dozent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kursname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("inhalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kurse");
                });
#pragma warning restore 612, 618
        }
    }
}
